"""Compiles GEMM kernels and generates the C++ table that describes them."""

load("//tools:spirv.bzl", "glslang_shader")

def _table_impl(ctx):
    table = ctx.actions.declare_file(ctx.label.name + ".inc")
    ctx.actions.write(table, ctx.attr.content)
    return [DefaultInfo(files = depset([table]))]

_table = rule(
    implementation = _table_impl,
    attrs = {"content": attr.string(mandatory = True)},
)

def _symbol(name):
    return "k" + "".join([c if c.isalnum() else "_" for c in name.elems()])

def _bool(value):
    return "true" if value else "false"

def gemm_kernels(name, kernels):
    """Compiles each kernel's shader and generates `gemm/<name>.inc`.

    The generated file defines the SPIR-V arrays and an array of gemm::Variant
    named after the table (`kVariants` for "variants"), for gemm/bench.cc to
    include.

    Args:
      name: the table's target name.
      kernels: dicts with "name" (the shader target), "src", "defines",
        optionally "hdrs" (included GLSL files), and
        "variants": dicts with "label", "precision" (a gemm::Precision
        enumerator's name), "block_m", "block_n", "k_multiple", and optionally
        "b_image", "texel_bytes", "max_m", "a_image", "raster", "split", and
        "subgroups" (per workgroup).
    """
    shaders = []
    arrays = []
    rows = []
    for kernel in kernels:
        glslang_shader(
            name = kernel["name"],
            src = kernel["src"],
            hdrs = kernel.get("hdrs", []),
            defines = kernel["defines"],
        )
        shaders.append(":" + kernel["name"])
        symbol = _symbol(kernel["name"])
        arrays.append('constexpr std::uint32_t {}[] =\n#include "{}/{}.inc"\n    ;\n'.format(
            symbol,
            native.package_name(),
            kernel["name"],
        ))
        for v in kernel["variants"]:
            rows.append('    {{"{}", Precision::{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}}},\n'.format(
                v["label"],
                v["precision"],
                symbol,
                v["block_m"],
                v["block_n"],
                v["k_multiple"],
                _bool(v.get("b_image", False)),
                v.get("texel_bytes", 16),
                v.get("max_m", 0),
                _bool(v.get("a_image", False)),
                _bool(v.get("raster", False)),
                _bool(v.get("split", False)),
                v.get("subgroups", 1),
            ))
    _table(
        name = name + "_table",
        content = "// Generated by gemm/kernels.bzl from gemm/BUILD.bazel.\n" +
                  "".join(arrays) + "\nconstexpr Variant k{}[] = {{\n".format(name.capitalize()) +
                  "".join(rows) + "};\n",
    )
    native.filegroup(
        name = name,
        srcs = shaders + [":" + name + "_table"],
    )
