load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "runtime_test",
    size = "small",
    srcs = ["runtime_test.cc"],
    copts = ["-fno-assume-sane-operator-new"],
    linkopts = [
        "-Wl,--wrap=malloc",
        "-Wl,--wrap=aligned_alloc",
    ],
    linkstatic = True,
    target_compatible_with = ["@platforms//os:android"],
    deps = [":support"],
)

cc_library(
    name = "support",
    hdrs = [
        "owner.h",
        "result.h",
    ],
    visibility = ["//visibility:public"],
    deps = select({
        "@platforms//os:android": ["@libcxx_runtime//:runtime"],
        "//conditions:default": [],
    }),
)
